version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
python:
   version: 3.8
   system_packages: true
   install:
      - requirements: docs/requirements_1.txt
      - method: setuptools
        path: .

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Build HTML only
formats:
   - htmlzip

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
      - requirements: docs/requirements_1.txt
      - method: setuptools
        path: .